.MODEL SMALL
.STACK 100H
.DATA
    TBAO1 DB 10,13, 'NHAP SO THU NHAT: $'
    TBAO2 DB 10,13, 'NHAP SO THU HAI: $'
    TBAO3 DB 10,13, 'TONG CUA 2 SO LA:$'  
    
    NUM1 DB ?  ; KHAI BAO DE GAN CAC GIA TRI
    NUM2 DB ?
    TONG DB ?

.CODE
   ; LAY DU LIEU TU DATA VAO DS
   MOV AX, DATA
   MOV DS,AX   
   
   ;XUAT TBAO1 RA MAN HINH 
   MOV AH,9H
   LEA DX,TBAO1
   INT 21H  
     
   ;NHAP 1 KI TU VAO BAN PHIM
   MOV AH,1H
   INT 21H  
   SUB AL,30H  ;LAY AL-30 VA LUU VAO AL 
               ; TA CHUYEN KI TU CHAR VE SO VI TA NHAP VAO THI NO LA 1 KI TU
   MOV NUM1,AL ; GAN NUM1=AL    
   
   ;XUAT TBAO2 RA MAN HINH
   MOV AH,9H
   LEA DX,TBAO2
   INT 21H
   
   MOV AH,1H
   INT 21H  
   SUB AL,30H
   MOV NUM2,AL
  
   ; XUAT THONG BAO TINH TONG
   MOV AH,9H
   LEA DX,TBAO3
   INT 21H
   
   ; TINH TONG
   MOV AL, NUM1  ; GAN SUM1 VAO AL DE CONG DUOC
   MOV BL, NUM2 
   ADD AL,BL   
   ADD AL,30H
   MOV TONG,AL
   
   ;XUAT RA MAN HINH
   MOV AH,2H
   MOV DL,TONG
   INT 21H
         
   ;THOAT CHUONG TRINH
   MOV AH,4CH
   INT 21H   ; LA LENH NGAT GIONG NHU DAU ; TRON C++
   
 END